services:
  - type: web
    name: silentconcierge
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DISCORD_TOKEN
        sync: false
